### PR TITLE
Add anchors to each table row

### PR DESCRIPTION
**Pull request by FlorianSW**
This allows to link to a specific line of the list.

### CODE REVIEW

**Comment by nemobis** [comment]
Are you sure that an anchor with "@" will work well? A bit noisy but ok, let's try.

**Comment by FlorianSW** [comment]
That's not a problem at all in HTML5, see:
https://www.w3.org/TR/html5/dom.html#the-id-attribute

And MediaWiki should handle any possible value, as far as I know (spaces are replaced by underscores, @ signs by .40 and so on), so there shouldn't be a big problem :)

btw.: Thanks for merging!

**Comment by mzmcbride** [comment]
Thank you for the pull request and merge.

Are you sure this change works? Due to the way we're doing string interpolation in this file, I would think you would need to specify `row[0]` again or risk raising a `TypeError` here.

We may want or need to use `{{anchorencode:}}` (or some kind of similar local wrapper template), but if the current code works, it seems fine to me.

**Comment by mzmcbride** [comment]
I fixed the `TypeError` in d4775745be846f79cf831f7676a648266e558496.

I logged in to `tools.gerrit-reports@tools-bastion-05` and updated the local clone at `/data/project/gerrit-reports/gerrit-reports` and re-ran this report. Links such as <https://www.mediawiki.org/wiki/Gerrit/Reports/Changesets_by_owner#MZMcBride> now work as expected.

**Comment by FlorianSW** [comment]
oh dear, stupid fault the missing `row[0]`, thanks for fixing! :)

**Pull request merged**
